name: Deploy Angular App to Windows EC2 via IIS

on:
  push:
    branches:
      - main  # Triggers deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular project
        run: npm run build --prod

      - name: Deploy to EC2 (Windows + IIS)
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: Administrator
          EC2_HOST: 65.1.248.103
        run: |
          # Save SSH private key
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Compress Angular build into a zip file
          cd dist
          zip -r angular-app.zip angular-app
          cd ..

          # Upload the zip file to EC2
          scp -v -o StrictHostKeyChecking=no -i private_key.pem dist/angular-app.zip $EC2_USER@$EC2_HOST:C:/angular-app.zip

          # Remotely backup existing site and deploy new build
          ssh -v -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "powershell.exe -Command \"
            \$timestamp = Get-Date -Format yyyyMMdd_HHmmss;
            \$backupPath = 'C:\\inetpub\\wwwroot\\angular-app_backup_' + \$timestamp;
            if (Test-Path 'C:\\inetpub\\wwwroot\\angular-app') {
              Rename-Item 'C:\\inetpub\\wwwroot\\angular-app' \$backupPath
            }
            Expand-Archive -Path 'C:\\angular-app.zip' -DestinationPath 'C:\\inetpub\\wwwroot' -Force;
            Remove-Item 'C:\\angular-app.zip';
            iisreset;
          \""
