name: Deploy Angular App to Windows EC2 via IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular project
        run: npm run build --prod

      - name: Zip build output
        run: |
          cd dist
          zip -r ../../angular-app.zip ./angular-sample-small-project
          cd ..

      - name: Deploy to EC2 IIS with backup and restart
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: Administrator
          EC2_HOST: 65.1.248.103
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Upload the zip file to EC2
          scp -o StrictHostKeyChecking=no -i private_key.pem angular-app.zip $EC2_USER@$EC2_HOST:C:/angular-app.zip

          # SSH into EC2 and run PowerShell commands to backup, extract, delete zip and restart IIS
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST powershell.exe -NoProfile -Command "
            \$timestamp = Get-Date -Format yyyyMMdd_HHmmss;
            \$backupPath = 'C:\\inetpub\\wwwroot\\angular-app_backup_' + \$timestamp;
            if (Test-Path 'C:\\inetpub\\wwwroot\\angular-sample-small-project') {
              Rename-Item 'C:\\inetpub\\wwwroot\\angular-sample-small-project' \$backupPath;
            }
            Expand-Archive -Path 'C:\\angular-app.zip' -DestinationPath 'C:\\inetpub\\wwwroot' -Force;
            Remove-Item 'C:\\angular-app.zip';
            iisreset;
          "
