name: Deploy Angular App to Windows EC2 via IIS

on:
  push:
    branches:
      - main  # Trigger deployment only on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular project
        run: npm run build --prod

      - name: Deploy to EC2 (IIS)
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: Administrator
          EC2_HOST: 65.1.248.103
        run: |
          # Save the private key and set permissions
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Transfer build files to Windows EC2 IIS directory
          scp -v -o StrictHostKeyChecking=no -i private_key.pem -r dist/* $EC2_USER@$EC2_HOST:"C:/inetpub/wwwroot/angular-app"

          # Remotely restart IIS using PowerShell
          ssh -v -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "powershell.exe -Command 'iisreset'"
