name: Deploy Angular App to Windows EC2 via IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular project
        run: npm run build --prod

      - name: Deploy to EC2 (IIS)
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: Administrator
          EC2_HOST: 65.1.248.103
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Copy build folder contents to IIS folder on EC2
          scp -o StrictHostKeyChecking=no -i private_key.pem -r dist/angular-sample-small-project/* $EC2_USER@$EC2_HOST:"C:/inetpub/wwwroot/angular-sample-small-project/"

          # Restart IIS on EC2
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST powershell.exe -Command "iisreset"
